# MISC
AGE_CLASS = ('AklZ', )

# MEETING
MEETING_NAME = ('KopfZ11', )

# RESULT
RESULT_ATHLETE_NAME = ('blENameASg', )

# EVENT
EVENT_NAME = ('blEWettb', )
EVENT_DAY = ('blEDatum', )
EVENT_TYPE = ('blEDis', )
EVENT_DESCRIPTION = EVENT_NAME + EVENT_DAY + EVENT_TYPE
