class CosaResource:
    """
    Abstract resource generated by COSA WIN

    Defines available query operations on a concrete resource.
    """

    def athlete(self, first_name=None, last_name=None, year_of_birth=None):
        raise NotImplementedError

    def meeting(self):
        raise NotImplementedError
